version: "3.9"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webakademia57
      MYSQL_USER: webakademia57
      MYSQL_PASSWORD: webakademia57
    ports:
      - "3309:3306"
    # volumes:
    #  - ./mysqlstore:/var/lib/mysql/
  mysql8:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webakademia80
      MYSQL_USER: webakademia80
      MYSQL_PASSWORD: webakademia80
    ports:
      - "3308:3306"
  postgress:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgress_db
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: cms
    ports:
      - 5432:5432
  php:
    # image: php:8.0-apache
    build:
      context: dockerfiles/8/
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: webakademia_php
    links:
      - mysql:mysql
      - mysql8:mysql8
      - postgress:postgress
    volumes:
      - ./:/var/www
      - ./logsphp80:/var/log/
    ports:
      - "8000:80"
  # php7:
  #   image: php:7.4-apache
  #   container_name: webakademia_php7
  #   links:
  #     - mysql:mysql
  #     - mysql8:mysql8
  #     - postgress:postgress
  #   volumes:
  #     - ./:/var/www
  #     - ./logsphp7:/var/log/
  #   ports:
  #     - "8001:80"
  # php5:
  #   image: php:5.6-apache
  #   container_name: webakademia_php5
  #   links:
  #     - mysql:mysql
  #     - mysql8:mysql8
  #     - postgress:postgress
  #   volumes:
  #     - ./:/var/www
  #     - ./logsphp5:/var/log/
  #   ports:
  #     - "8002:80"